# Generated by Django 2.2 on 2020-04-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('rate', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('start_h', models.TimeField()),
                ('end_h', models.TimeField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
